import type { OpenAPIV3 } from 'openapi-types';
const adminSec = [{ BearerAuth: [] }];
const staffSec = [{ BearerAuth: [] }];
const err = { '400': { $ref: '#/components/responses/ValidationError' }, '401': { $ref: '#/components/responses/UnauthorizedError' }, '403': { $ref: '#/components/responses/ForbiddenError' } } as any;
const logParams: OpenAPIV3.ParameterObject[] = [
  { name:'user', in:'query', schema:{ type:'string', enum:['Admin','Operation Manager','Staff','System'] } },
  { name:'action', in:'query', schema:{ type:'string', enum:['Created','Updated','Deleted','Assigned','Approved','Triggered','Submitted','Attempted','Sent','Cancelled'] } },
  { name:'module', in:'query', schema:{ type:'string', enum:['Clients','Staff','Visits','Bookings','Messages','Settings','Alerts','Notification','Check-in','Visit logs','Service'] } },
  { name:'dateRange', in:'query', schema:{ type:'string', enum:['Today','Yesterday','Last 7 Days','Last 30 Days','This Month','Custom Range'] } },
  { name:'startDate', in:'query', schema:{ type:'string', format:'date' } },
  { name:'endDate', in:'query', schema:{ type:'string', format:'date' } },
  { name:'search', in:'query', schema:{ type:'string' } }
];
const json = (schema:any, example:any) => ({ required:true, content:{ 'application/json':{ schema, example } } });
export const profileSettingsPaths: OpenAPIV3.PathsObject = {
  '/staff/profile': { get: { tags:['Staff Profile'], summary:'Get authenticated staff profile', security:staffSec, responses:{ '200':{ description:'Staff profile retrieved', content:{'application/json':{ schema:{ $ref:'#/components/schemas/StaffProfile' }, example:{ success:true,message:'Staff profile retrieved',data:{ name:'Sarah Johnson',initials:'SJ',role:'Support Worker',email:'sarah@dailyassist.test',gender:'Female',phone:'+441234567890',dob:'1992-04-12',staffId:'STF-001',zone:'Basildon',accountStatus:'Active',lastLoginAt:'2026-07-22T09:45:00.000Z' } } } } }, ...err } } },
  '/admin/profile': { get:{ tags:['Admin Profile'], summary:'Get authenticated admin profile', security:adminSec, responses:{ '200':{ description:'Admin profile retrieved' }, ...err } }, patch:{ tags:['Admin Profile'], summary:'Update authenticated admin profile', security:adminSec, requestBody:{ required:true, content:{ 'application/json':{ schema:{ type:'object', properties:{ firstName:{type:'string'}, lastName:{type:'string'}, photo:{type:'string',description:'Base64 data URL or URL'} }, additionalProperties:false }, example:{ firstName:'John', lastName:'Admin' } }, 'multipart/form-data':{ schema:{ type:'object', properties:{ firstName:{type:'string'}, lastName:{type:'string'}, photo:{type:'string',format:'binary'} } } } } }, responses:{ '200':{ description:'Admin profile updated' }, ...err } } },
  '/admin/account': { delete:{ tags:['Admin Profile'], summary:'Deactivate authenticated admin account', security:adminSec, requestBody:json({ type:'object', required:['confirm'], properties:{ confirm:{ type:'boolean', enum:[true] } } }, { confirm:true }), responses:{ '204':{ description:'Account deactivated; sessions invalidated' }, ...err } } },
  '/admin/notification-settings': { get:{ tags:['Admin Settings'], summary:'Get admin notification settings', security:adminSec, responses:{ '200':{ description:'Notification settings retrieved' }, ...err } }, patch:{ tags:['Admin Settings'], summary:'Update admin notification settings', security:adminSec, requestBody:json({ type:'object', properties:{ bookingRequest:{type:'boolean'}, staffCheckin:{type:'boolean'}, staffCheckout:{type:'boolean'}, missedCheckin:{type:'boolean'}, missedCheckout:{type:'boolean'} } }, { bookingRequest:true, staffCheckin:true, staffCheckout:false, missedCheckin:true, missedCheckout:true }), responses:{ '200':{ description:'Notification settings updated' }, ...err } } },
  '/admin/system-log': { get:{ tags:['System Log'], summary:'List system log entries', security:adminSec, parameters:[...logParams, {name:'page',in:'query',schema:{type:'integer',default:1}}, {name:'pageSize',in:'query',schema:{type:'integer',default:10}}], responses:{ '200':{ description:'System log retrieved' }, ...err } } },
  '/admin/system-log/export': { get:{ tags:['System Log'], summary:'Export filtered system log as CSV or PDF', security:adminSec, parameters:[...logParams, {name:'format',in:'query',required:true,schema:{type:'string',enum:['csv','pdf']}}], responses:{ '200':{ description:'System log export', content:{ 'text/csv':{ schema:{type:'string'} }, 'application/pdf':{ schema:{type:'string',format:'binary'} } } }, ...err } } },
  '/admin/roles-permissions': { get:{ tags:['Admin Settings'], summary:'Get role permission sets', security:adminSec, responses:{ '200':{ description:'Roles and permissions retrieved' }, ...err } } }
};
